//Actions for Posts
export const GET_POSTS = "GET_POSTS";
export const ADD_POSTS = "ADD_POSTS";
export const DELETE_POSTS = "DELETE_POSTS";
export const POSTS_LOADING = "POSTS_LOADING";



//Action to get Items
export const GET_ITEMS = "GET_ITEMS";
export const GET_LOCATION = "GET_LOCATION";
export const UPDATE_CART = "UPDATE_CART";
export const GET_HOMESCREENDATA = "GET_HOMESCREENDATA";
export const GET_USERDATA = "GET_USERDATA";
export const UPDATE_USER_DETAILS="UPDATE_USER_DETAILS";
export const GET_CATEGORIESDATA = "GET_CATEGORIESDATA";
export const GET_USERORDER = "GET_USERORDER";
export const GET_USERPASTORDER = "GET_USERPASTORDER";
export const GET_USERADDRESS = "GET_USERADDRESS";
export const GET_NOTIFYBY = "GET_NOTIFYBY"; 
export const UPDATE_NOTIFYBY ="UPDATE_NOTIFYBY";
export const GET_CURRENCY ="GET_CURRENCY";
export const GET_ALLPRODUCTS="GET_ALLPRODUCTS";
export const GET_DELIVERYDATA ="GET_DELIVERYDATA";
export const GET_ORDERFEILDS = "GET_ORDERFEILDS";
export const GET_COUPONDISCOUNT = "GET_COUPONDISCOUNT";
export const GET_STOREID = "GET_STOREID";